## Abstract {.unnumbered}

###### Introduction
The Aligned Rank Transform (ART) is a popular statistical method, commonly used when the statistical assumptions of parametric procedures, such as normality assumptions, are not met. Its popularity stems from several Monte Carlo experiments demonstrating that the method is robust and powerful. However, contrary experimental findings suggest that ART may be less robust compared to simpler rank transformation methods, failing to adequately control Type I error rates across various scenarios, including discrete data, skewed distributions, and distributions with unequal variances. These results have not gained attention within the Human-Computer Interaction community, where ART is routinely used.

###### Objectives
This research aims to clarify the contradictory findings from previous studies by reevaluating the robustness and effectiveness of ART. Its complementary goal is to investigate the performance of alternative nonparametric methods.

###### Methods
We conducted a series of Monte Carlo experiments to systematically evaluate ART across various data distributions and experimental designs. Our comparative analysis includes two alternative transformation methods: the simple rank transformation and the inverse normal transformation, along with parametric ANOVA without transformation. Additionally, we present supplementary experiments involving other competitive nonparametric methods in the [appendix](appendix.html).

Our experimental methodology builds upon a latent variable modeling approach, enabling us to simulate main and interaction effects across diverse distributions and address interpretation issues related to these effects. In addition to Monte Carlo experiments, we explore the behavior of ART through illustrative examples and reanalyze data from previous user studies.

###### Results
Our results indicate that ART systematically confounds effects across all the experimental designs we examined. Specifically, an effect on one factor may cause ART to incorrectly detect effects on other factors or their interactions. We show that the method fails under various conditions, including skewed distributions, binomial distributions, Likert-type data with five or seven ordinal levels, distributions with unequal variances, and experimental designs with missing data.

Surprisingly, ART operates as expected only under normal distributions with equal variances. In all other scenarios, it performs less effectively than simpler rank transformations and, in many situations, such as with ordinal data, it is significantly worse than parametric ANOVA. Our analysis of real-world data further demonstrates that using ART often leads to incorrect conclusions. Conversely, the inverse normal transformation emerges as the most versatile and robust nonparametric method, although we identify situations in which this method can also inflate errors or distort effects.

In addition, our results show that testing interactions in the presence of multiple main effects is challenging for all methods. We raise awareness about previous warnings regarding the interpretation of *removable interactions*. 

###### Conclusion
We conclude that ART is a flawed statistical method and should be abandoned. We recommend prioritizing parametric methods, including linear models and their generalizations. While we propose the inverse normal transformation as a generic nonparametric alternative, we caution researchers about risks and limitations of rank transformation methods.

###### Materials
We provide [supplementary materials](https://github.com/journalovi/2024-tsandilas-ranktransforms/tree/main/supplementary) with experimental code, raw experimental results, and detailed analyses of examples and case studies presented throughout the article. Source files of our article, appendix, and supplementary materials can also be found on OSF at [https://osf.io/hs7j8](https://osf.io/hs7j8). 
:::

::: {.callout-note appearance="simple" icon=false collapse=true}
## Materials, Authorship, License, Conflicts

###### Research materials

We provide [supplementary materials](https://github.com/journalovi/2024-tsandilas-ranktransforms/tree/main/supplementary) with experimental code, raw experimental results, and detailed analyses of examples and case studies presented throughout the article. Source files of our article, appendix, and supplementary materials can also be found on OSF at [https://osf.io/hs7j8](https://osf.io/hs7j8). 

###### Authorship

**Theophanis Tsandilas:** Conceptualization, Methodology, Resources, Software, Formal Analysis, Investigation, Validation, Data Curation, Vizualization, Writing - Original Draft, Writing - Review & Editing.
**Géry Casiez:** Conceptualization, Investigation, Writing - Review & Editing.

###### License

This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

###### Conflicts of interest

The authors declare that there are no competing interests.

:::
