## Conclusions {#conclusions}
The Align Rank Transformation (ART) was introduced as a remedy for interaction effect distortions caused by the simple rank transformation [@conover:1981]. Early simulation experiments demonstrated ART's robustness for 2-factorial designs, while subsequent tools such as ARTool [@wobbrock:2011;@elkin:2021] extended its application to multifactorial designs, for testing main effects, interactions, and contrasts. The ARTool has gained significant traction, particularly within the fields of Human-Computer Interaction, Augmented Reality, and Virtual Reality, and has been used in the analysis of over a thousand user studies.

However, our experimental findings and examples reveal that ART is defective, performing adequately only under the strict assumptions of linearity, continuous responses with equal variances among groups, and balanced designs. These results corroborate previous warnings regarding ART's performance [@luepsen:2017;@luepsen:2018], leading us to conclude that the method should be abandoned. We recommend prioritizing parametric methods. While we propose the inverse normal transformation (INT) as a generic nonparametric alternative, we identify situations in which this method may also fail. Finally, we caution researchers about the interpretation of interactions. 